### PR TITLE
Fix crash when trying to (de)activate a behavior on an object that doesn't have the behavior + bonus

### LINKED ISSUE #243: Crash when trying to disable a behavior not affected to an object from events
When you try to disable a behavior on an object that doesn't have the behavior, GDevelop crashes.

### PR DESCRIPTION
**Pull request by victorlevasseur**
Fix #243 by testing if the behavior exists.
Also replaces ```std::map<gd::String, Behavior*>``` with ```std::map<gd::String, std::unique_ptr<Behavior>>``` so there is no need to manually delete the behaviors. ```GetBehaviorRawPointer``` still returns a raw pointer which is non-owning.

I may add another commit to add a templated function to do a deep copy of ```std::map<K, std::unique_ptr<T>>``` and ```std::vector<std::unique_ptr<T>>``` (good idea ?).

### CODE REVIEW

**Comment by victorlevasseur** [comment]
By the way, returning a ```std::unique_ptr``` from ```gd::Project::CreateBehavior``` won't be a be idea (and using the move semantic to add it to the objects).

File: Core/GDCore/Project/Object.cpp [hunk 1]
```diff
@@ -21,9 +21,7 @@ namespace gd
 
 Object::~Object()
 {
-    //Do not forget to delete behaviors which are managed using raw pointers.
```
Comment (4ian) [inline Core/GDCore/Project/Object.cpp]: \o/ Love this

**Comment by 4ian** [comment]
> Also replaces std::map<gd::String, Behavior*> with std::map<gd::String, std::unique_ptr<Behavior>> so there is no need to manually delete the behaviors.

Nice! Love that it makes the code less error prone regarding manuall calls to delete. :+1: 

> By the way, returning a std::unique_ptr from gd::Project::CreateBehavior won't be a be a bad idea too (and using the move semantic to add it to the objects).

Yep, that would be better!

> I may add another commit to add a templated function to do a deep copy of std::map<K, std::unique_ptr<T>> and std::vector<std::unique_ptr<T>> (good idea ?).

Mmmm, not sure about it, let's not over-engineer this but if it's used and make the code of RuntimeObject simpler that could be a good idea.

**Comment by victorlevasseur** [comment]
> Mmmm, not sure about it, let's not over-engineer this but if it's used and make the code of RuntimeObject simpler that could be a good idea.
The code to copy the ```std::vector/map``` with ```std::unique_ptr``` is used multiple times, that's why a function could be good. This would avoid to have loops to copy the pointed objects.

**Comment by victorlevasseur** [comment]
The last commit 21dcb39 replaces ```Behavior*``` with ```std::unique_ptr<Behavior>``` in ```CreateBehavior``` in ```gd::Platform```, ```gd::PlatformExtension``` and ```gd::Project```.

**Comment by 4ian** [comment]
Great! Merging this now :) Thanks! :+1:
